# Generated by Django 5.1.7 on 2025-03-13 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiario',
            fields=[
                ('cedula', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('poblacion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'beneficiarios',
            },
        ),
    ]
